### ISSUE TITLE
🐞 错误报告 

### ISSUE THREAD

**Issue by sl-knowledge** [JimmyLv/BibiGPT-v1#185]
# 错误报告 🐞

如果您在使用此项目时遇到了错误，请在此报告，我们会尽快解决此问题。

## 错误描述 🤔

请详细地描述您遇到的问题，包括出现问题的环境和步骤，以及您已经尝试过的解决方法。

另外，如果您在解决问题时已经查看过其他 GitHub Issue，请务必在文本中说明并引用相关信息。

## 附加信息 📝

请提供以下信息以帮助我们更快地解决问题：

- 输出日志，包括错误信息和堆栈跟踪
- 相关的代码片段或文件
- 您的操作系统、软件版本等环境信息

感谢您的反馈！🙏

<img width="1023" alt="image" src="https://github.com/user-attachments/assets/df82e1c6-9588-48c5-b267-ece2d68b2bfd">

**Comment by sl-knowledge** [comment]
错误信息：

Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
组件堆栈：


    at T (https://bibigpt.co/_next/static/chunks/8052-2cd462ba61ec5bf8.js:1:5605)
    at div
    at https://bibigpt.co/_next/static/chunks/pages/_app-a498ccf5a5238fbe.js:34:19359
    at s (https://bibigpt.co/_next/static/chunks/pages/_app-a498ccf5a5238fbe.js:34:16567)
    at https://bibigpt.co/_next/static/chunks/8130-88a112e89aa13682.js:1:5619
    at https://bibigpt.co/_next/static/chunks/6937-160cef1ba2f40be1.js:1:23984
    at div
    at https://bibigpt.co/_next/static/chunks/pages/_app-a498ccf5a5238fbe.js:34:19359
    at s (https://bibigpt.co/_next/static/chunks/pages/_app-a498ccf5a5238fbe.js:30:154572)
    at https://bibigpt.co/_next/static/chunks/8130-88a112e89aa13682.js:1:4216
    at el (https://bibigpt.co/_next/static/chunks/8052-2cd462ba61ec5bf8.js:1:11185)
    at div
    at eu (https://bibigpt.co/_next/static/chunks/8052-2cd462ba61ec5bf8.js:1:17731)
    at div
    at div
    at E (https://bibigpt.co/_next/static/chunks/6386-ea91a13776ea6f11.js:1:1041)
    at div
    at eE (ht

**Comment by JimmyLv** [comment]
查看思维导图时会报错，已修复
